### ISSUE TITLE
CTS chart clobbering LOADER_PATH of base image

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria-charts#121]
The default CTS `values.yaml` file is insufficient to successfully run the CTS with only the default values therein, because it refers to the Graph repository connector and this connector must now be downloaded separately (no longer embedded in the Egeria images).

Fix should be relatively straightforward:

- Add a `downloads.url` value that points to the location for downloading the latest released version of the graph connector (from https://search.maven.org/artifact/org.odpi.egeria/graph-repository-connector)

**Comment by cmgrote** [comment]
As discussed on Feb 3 call, the Graph repository connector jar actually _is_ there in the image, it's just in a different directory -- and currently the CTS chart is clobbering the `LOADER_PATH` location set inside the container with its own `LOADER_PATH`. This could be causing broader issues as well.

Idea discussed on call was to use a `LOADER_PATH_PREPEND` and / or a `LOADER_PATH_APPEND` variable instead in the CTS chart to setup additional locations that should be added to `LOADER_PATH` rather than overwriting it.

**Comment by cmgrote** [comment]
@planetf1 ^^ FYI

As I think you were mentioning, maybe a quick _initial_ win (and test) will be simply to update the CTS chart with a `LOADER_PATH` that includes both the default location (from in-image) + my extended location. (Just means that if we ever change the location in-image we need to remember to change this chart accordingly as well.) But this would save us from needing to either update the base image to include a startup script that does these pre-/appends or inject such a script as part of k8s (both seem more cumbersome or hack-y in the short-term).

**Comment by planetf1** [comment]
@cmgrote - yes, just include both paths in LOADER_PATH in the cts chart (and pts?) is sufficient to fix the problem.

A possible enhancement would be to the docker image, where we would add more flexibility in prepend/append/replace the path through additional variables, like LOADER_PATH_PREPEND etc. The UBI-8 openjdk image we use from redhat does something similar for some settings.

That would be an enabling change in base egeria, but might require a change to how the jar is launched - we'd need to run a script (to build the path) instead of the jar directly.

Happy to keep that part open - either via new issue or redirection of this one. 

Another aspect is that the user of LOADER_PATH is not mentioned. This should be covered in the docs for the docker image (which need writing). Perhaps do what you feel reasonable for your needs, and feel free to assign back to me to add any additional pieces?

**Comment by cmgrote** [comment]
Thanks, I will submit the basic update I outlined above later; but unfortunately even that didn't seem to solve the strange failures I see on typedef events.

I can't see anything obviously different from the Notebooks setup, either.

I'm pretty sure I can repro the events error even just running locally and natively outside any containers, so it's not clear to me why the Notebooks would work (but I don't have a sufficient k8s environment to try to run everything in the lab to test in-Notebook, either).

Any other ideas on places to look? Or could you have a try locally / with the CTS chart (once I make the basic change)?

**Comment by planetf1** [comment]
I merged this commit now so think we can close
