### ISSUE TITLE
Jupyter failing to start in lab chart

### ISSUE THREAD

**Issue by dwolfson** [odpi/egeria-charts#213]
I update my charts and restarted my k8s. All pods came up except Jupyter. Looking at the log file for the pod it says:

Entered start.sh with args: jupyter lab --notebook-dir=/home/jovyan/work
/usr/local/bin/start.sh: running hooks in /usr/local/bin/before-notebook.d as uid / gid: 1000 / 100
/usr/local/bin/start.sh: running script /usr/local/bin/before-notebook.d/setup-notebooks.sh
-- Setting up Egeria notebooks --
Sleeping for 0 seconds
No git repo found in /home/jovyan/work, cloning from https://github.com/odpi/egeria-jupyter-notebooks...
Cloning into '/home/jovyan/work'...
fatal: unable to access 'https://github.com/odpi/egeria-jupyter-notebooks/': SSL: certificate subject name (wolfsonnet.synology.me) does not match target host name 'github.com'

**Comment by planetf1** [comment]
This last error indicates that when the git client running within the jupyter container tried to connect to github, it got a response to the TLS setup with a cert saying 'wolfsonnet.synology.me' rather than from github.com

ie, the outbound connection to github is somehow being responded to by something of yours.

This indicates something wrong in your DNS or routing setup / kubernetes infrastructure. This isn't related to egeria.

**Comment by planetf1** [comment]
did you resolve this? it very much looks like local networking issues
